/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animais;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Windows
 */
public class menu_b extends javax.swing.JFrame {
    banco_de_dados Data = new banco_de_dados();
    /**
     * Creates new form menu_b
     */
    public menu_b() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Campo_Peso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Campo_Nome = new javax.swing.JTextField();
        Adiciona_cavalo = new javax.swing.JButton();
        Adiciona_anfibio = new javax.swing.JButton();
        adiciona_animal = new javax.swing.JButton();
        Adiciona_reptil = new javax.swing.JButton();
        Adiciona_macaco = new javax.swing.JButton();
        Adiciona_humano = new javax.swing.JButton();
        Adiciona_mamifero = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel2.setText("Peso:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 40, 20);
        getContentPane().add(Campo_Peso);
        Campo_Peso.setBounds(70, 43, 70, 30);

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 40, 20);
        getContentPane().add(Campo_Nome);
        Campo_Nome.setBounds(70, 13, 70, 30);

        Adiciona_cavalo.setText("Cavalo");
        Adiciona_cavalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adiciona_cavaloActionPerformed(evt);
            }
        });
        getContentPane().add(Adiciona_cavalo);
        Adiciona_cavalo.setBounds(190, 210, 80, 60);

        Adiciona_anfibio.setText("Anfibio");
        Adiciona_anfibio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adiciona_anfibioActionPerformed(evt);
            }
        });
        getContentPane().add(Adiciona_anfibio);
        Adiciona_anfibio.setBounds(410, 130, 80, 50);

        adiciona_animal.setText("Animal");
        adiciona_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiciona_animalActionPerformed(evt);
            }
        });
        getContentPane().add(adiciona_animal);
        adiciona_animal.setBounds(263, 60, 90, 50);

        Adiciona_reptil.setText("Reptil");
        Adiciona_reptil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adiciona_reptilActionPerformed(evt);
            }
        });
        getContentPane().add(Adiciona_reptil);
        Adiciona_reptil.setBounds(270, 130, 85, 50);

        Adiciona_macaco.setText("Macaco");
        Adiciona_macaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adiciona_macacoActionPerformed(evt);
            }
        });
        getContentPane().add(Adiciona_macaco);
        Adiciona_macaco.setBounds(102, 208, 80, 60);

        Adiciona_humano.setText("Homem");
        Adiciona_humano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adiciona_humanoActionPerformed(evt);
            }
        });
        getContentPane().add(Adiciona_humano);
        Adiciona_humano.setBounds(16, 208, 80, 60);

        Adiciona_mamifero.setText("Mamifero");
        Adiciona_mamifero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adiciona_mamiferoActionPerformed(evt);
            }
        });
        getContentPane().add(Adiciona_mamifero);
        Adiciona_mamifero.setBounds(100, 130, 90, 50);

        setSize(new java.awt.Dimension(585, 355));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Adiciona_cavaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adiciona_cavaloActionPerformed
        Cavalo animal = new Cavalo();
        animal.setNome(this.Campo_Nome.getText());
        animal.setPeso(Float.parseFloat(this.Campo_Peso.getText()));

        try {
            this.Data.Adiciona_animal(animal);
        } catch (IOException ex) {
            Logger.getLogger(Adiciona_menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Adiciona_cavaloActionPerformed

    private void Adiciona_anfibioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adiciona_anfibioActionPerformed
        Anfibios animal = new Anfibios();
        animal.setNome(this.Campo_Nome.getText());
        animal.setPeso(Float.parseFloat(this.Campo_Peso.getText()));

        try {
            this.Data.Adiciona_animal(animal);
        } catch (IOException ex) {
            Logger.getLogger(Adiciona_menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Adiciona_anfibioActionPerformed

    private void adiciona_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adiciona_animalActionPerformed
        Animais animal = new Animais();
        animal.setNome(this.Campo_Nome.getText());
        animal.setPeso(Float.parseFloat(this.Campo_Peso.getText()));

        try {
            this.Data.Adiciona_animal(animal);
        } catch (IOException ex) {
            Logger.getLogger(Adiciona_menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adiciona_animalActionPerformed

    private void Adiciona_reptilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adiciona_reptilActionPerformed
        Reptil animal = new Reptil();
        animal.setNome(this.Campo_Nome.getText());
        animal.setPeso(Float.parseFloat(this.Campo_Peso.getText()));

        try {
            this.Data.Adiciona_animal(animal);
        } catch (IOException ex) {
            Logger.getLogger(Adiciona_menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Adiciona_reptilActionPerformed

    private void Adiciona_macacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adiciona_macacoActionPerformed
        Macaco animal = new Macaco();
        animal.setNome(this.Campo_Nome.getText());
        animal.setPeso(Float.parseFloat(this.Campo_Peso.getText()));

        try {
            this.Data.Adiciona_animal(animal);
        } catch (IOException ex) {
            Logger.getLogger(Adiciona_menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Adiciona_macacoActionPerformed

    private void Adiciona_humanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adiciona_humanoActionPerformed
        Homem animal = new Homem();
        animal.setNome(this.Campo_Nome.getText());
        animal.setPeso(Float.parseFloat(this.Campo_Peso.getText()));

        try {
            this.Data.Adiciona_animal(animal);
        } catch (IOException ex) {
            Logger.getLogger(Adiciona_menu.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Adiciona_humanoActionPerformed

    private void Adiciona_mamiferoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adiciona_mamiferoActionPerformed
        Mamifero animal = new Mamifero();
        animal.setNome(this.Campo_Nome.getText());
        animal.setPeso(Float.parseFloat(this.Campo_Peso.getText()));
        //System.out.println("--->" + animal.getTipo());
        try {
            this.Data.Adiciona_animal(animal);
        } catch (IOException ex) {
            Logger.getLogger(Adiciona_menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Adiciona_mamiferoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_b().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adiciona_anfibio;
    private javax.swing.JButton Adiciona_cavalo;
    private javax.swing.JButton Adiciona_humano;
    private javax.swing.JButton Adiciona_macaco;
    private javax.swing.JButton Adiciona_mamifero;
    private javax.swing.JButton Adiciona_reptil;
    private javax.swing.JTextField Campo_Nome;
    private javax.swing.JTextField Campo_Peso;
    private javax.swing.JButton adiciona_animal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
