/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jogodavelha;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Cliente Preferencial
 */
public class Tela_Login extends javax.swing.JFrame {

    /** Creates new form Tela_Login */
    public Tela_Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NickName_recebido_1 = new javax.swing.JTextField();
        Botão_Entrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NickName_recebido_2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome do Jogador 1:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 180, 14);

        NickName_recebido_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NickName_recebido_1ActionPerformed(evt);
            }
        });
        getContentPane().add(NickName_recebido_1);
        NickName_recebido_1.setBounds(50, 40, 179, 30);

        Botão_Entrar.setText("Entrar");
        Botão_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão_EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(Botão_Entrar);
        Botão_Entrar.setBounds(170, 120, 63, 23);

        jLabel2.setText("Nome do Jogador 2:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 70, 180, 14);

        NickName_recebido_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NickName_recebido_2ActionPerformed(evt);
            }
        });
        getContentPane().add(NickName_recebido_2);
        NickName_recebido_2.setBounds(50, 90, 179, 30);

        setSize(new java.awt.Dimension(282, 196));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NickName_recebido_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NickName_recebido_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NickName_recebido_1ActionPerformed

    private void NickName_recebido_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NickName_recebido_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NickName_recebido_2ActionPerformed

    private void Botão_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão_EntrarActionPerformed
        JogoDaVelha jogo;
        try {
            jogo = new JogoDaVelha(this.NickName_recebido_1.getText(), this.NickName_recebido_2.getText());
            jogo.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Tela_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dispose();
    }//GEN-LAST:event_Botão_EntrarActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botão_Entrar;
    private javax.swing.JTextField NickName_recebido_1;
    private javax.swing.JTextField NickName_recebido_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
